Repository pre-onboarding-backend-E/03-BossRaid-E, pull requests merged in 2022-07, with the labels that each got.

#7 ADD / 레이드 상태 조회 API 생성
  src/raid/dto/raidStatusDto.ts
  src/raid/raid.controller.ts
  src/raid/raid.service.ts
Labels: enhancement

#13 ADD / 보스 레이드 시작 성공 구현
  .dockerignore
  .eslintrc.js
  .gitignore
  .prettierrc
  Dockerfile
  docker-compose.yaml
  dump.rdb
  nest-cli.json
  package.json
  src/app.module.ts
  src/auth/__test__/auth.service.spec.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/passport/guard/jwtAuthGuard.ts
  src/auth/passport/guard/jwtRefreshGuard.ts
  src/auth/passport/guard/localAuthGuard.ts
  src/auth/passport/strategy/jwtRefresh.strategy.ts
  src/auth/passport/strategy/jwtStrategy.ts
  src/auth/passport/strategy/localStrategy.ts
  src/common/baseResponse.dto.ts
  src/common/enterBossOption.interface.ts
  src/common/error.enum.ts
  src/common/error.response.ts
  src/common/getUserDecorator.ts
  src/common/httpError.type.ts
  src/common/response.enum.ts
  src/common/tokenOption.interface.ts
  src/config/baseApiDocs.ts
  src/main.ts
  src/raid/dto/createRaid.dto.ts
  src/raid/entities/raid.entity.ts
  src/raid/raid.controller.ts
  src/raid/raid.module.ts
  src/raid/raid.service.ts
  src/user/__test__/user.service.spec.ts
  src/user/dto/createUser.dto.ts
  src/user/dto/login.dto.ts
  src/user/dto/login.response.ts
  src/user/entities/user.entity.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: enhancement

#20 REFACTOR / 레이드 상태 조회 API 구현
  docker-compose.yaml
  src/common/response.enum.ts
  src/raid/dto/raidStatus.dto.ts
  src/raid/dto/raidStatusDto.ts
  src/raid/raid.controller.ts
  src/raid/raid.service.ts
  yarn.lock
Labels: enhancement

#25 MODIFY / 레이드 상태 조회 API 수정
  Dockerfile
  docker-compose.yaml
  src/raid/raid.controller.ts
  src/raid/raid.service.ts
Labels: enhancement

#26 ADD, REFACTOR / 유저 총 점수 및 레이드 기록 조회 Response 수정, 테스트 코드 작성
  docker-compose.yaml
  src/common/error.enum.ts
  src/config/sentryInterceptor.config.ts
  src/user/__test__/user.service.spec.ts
  src/user/dto/userInfo.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: enhancement

#30 REFACTOR / 레이드 상태조회 API 수정 및 에러 핸들링
  src/common/error.enum.ts
  src/raid/dto/raidStatus.dto.ts
  src/raid/raid.controller.ts
  src/raid/raid.service.ts
Labels: enhancement

#31 FIX / Raidstatus 수정에 따른 변경사항
  src/raid/raid.service.ts
Labels: fix

#43 FIX / User Api Nickname 중복 에러 처리 및 Sentry 에러 수정
  .github/workflows/release.yml
  .gitignore
  docker-compose.yaml
  src/common/error.enum.ts
  src/main.ts
  src/user/user.service.ts
Labels: bug, fix

#47 ADD / 레이드 시작 시 동시성 제어
  dump.rdb
  package.json
  src/raid/dto/raidEnter.dto.ts
  src/raid/dto/raidStatus.dto.ts
  src/raid/entities/raid.entity.ts
  src/raid/raid.consumer.ts
  src/raid/raid.controller.ts
  src/raid/raid.module.ts
  src/raid/raid.service.ts
  yarn.lock
Labels: enhancement

#44 MODIFY / 레이드 종료 시 레이드 기록을 레디스가 아닌 DB에서 가져오도록 변경
  src/common/error.enum.ts
  src/raid/dto/raidStatus.dto.ts
  src/raid/raid.module.ts
  src/raid/raid.service.ts
  src/user/user.service.ts
Labels: fix

#48 Redis 모듈 설치
  docker-compose.yaml
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/raid/raid.service.ts
  src/user/user.controller.ts
  yarn.lock
Labels: settings

#50 MODIFY / dto 이름 변경, utils 정리, 주석 정리
  src/auth/auth.service.ts
  src/auth/passport/strategy/jwtRefresh.strategy.ts
  src/auth/passport/strategy/jwtStrategy.ts
  src/auth/passport/strategy/localStrategy.ts
  src/common/baseResponse.dto.ts
  src/common/error.enum.ts
  src/common/getUserDecorator.ts
  src/raid/dto/raidEnter.dto.ts
  src/raid/dto/raidStatus.dto.ts
  src/raid/dto/topRankerList.dto.ts
  src/raid/dto/topRankerListRes.dto.ts
  src/raid/entities/raid.entity.ts
  src/raid/raid.controller.ts
  src/raid/raid.module.ts
  src/raid/raid.service.ts
  src/user/user.controller.ts
  src/user/user.service.ts
  src/utils/axiosHelper.ts
  src/utils/raid.consumer.ts
  yarn.lock
Labels: enhancement

#53 REFACTOR / 레이드 상태 조회 타입 수정
  src/raid/dto/raidStatus.dto.ts
  src/raid/raid.controller.ts
  src/raid/raid.service.ts
  src/raid/raidStatus.interface.ts
Labels: fix

#61 ADD / 보스 레이드 시작 동시성 제어
  package.json
  src/common/error.enum.ts
  src/raid/raid.module.ts
  src/raid/raid.service.ts
  src/utils/raid.consumer.ts
  yarn.lock
Labels: enhancement

#57 ADD / 랭킹 조회 api
  src/raid/dto/topRankerListRes.dto.ts
  src/raid/raid.controller.ts
  src/raid/raid.service.ts
  src/user/user.service.ts
Labels: enhancement

#64 FIX / error message 붙어 있지 않던 부분 수정
  src/raid/raid.service.ts
Labels: fix

#66 주석 추가, 폴더 정리
  src/raid/dto/raidStatusRes.dto.ts
  src/raid/raid.controller.ts
  src/raid/raid.service.ts
  src/raid/raidStatus.interface.ts
Labels: documentation

#67 CHORE / 폴더 구조 정리
  src/app.module.ts
  src/auth/auth.service.ts
  src/common/error.response.ts
  src/common/httpError.type.ts
  src/main.ts
  src/raid/raid.controller.ts
  src/raid/raid.module.ts
  src/raid/raid.service.ts
  src/user/dto/login.response.ts
  src/user/user.controller.ts
  src/user/user.service.ts
  src/utils/helper/axiosHelper.ts
  src/utils/helper/getUserDecorator.ts
  src/utils/helper/raid.consumer.ts
  src/utils/interface/enterBossOption.interface.ts
  src/utils/interface/tokenOption.interface.ts
  src/utils/responseHandler/baseResponse.dto.ts
  src/utils/responseHandler/error.enum.ts
  src/utils/responseHandler/response.enum.ts
  src/utils/responseHandler/response.interceptor.ts
Labels: refactor

#70 FIX, REFACRTOR / User Api Response 수정
  .dockerignore
  .github/workflows/release.yml
  .gitignore
  docker-compose.yaml
  src/user/dto/login.response.ts
  src/user/dto/user.response.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: bug, documentation, enhancement, fix

#73 ADD & FIX / axios 로직 공통화, 존재하지 않는 레이드 에러 처리
  src/common/error.enum.ts
  src/raid/raid.service.ts
  src/utils/responseHandler/error.enum.ts
Labels: enhancement, fix

#74 DOC / api 시연 gif 생성 / MODIFY / 레이드 서비스 유닛 테스트 코드 초안 작성
  .gitignore
  images/gif/랭크리스트 조회.gif
  images/gif/레이드 상태조회-입장가능.gif
  images/gif/레이드 상태조회-입장불가.gif
  images/gif/레이드 입장.gif
  images/gif/레이드 종료.gif
  images/gif/로그인.gif
  images/gif/종료 후 다시 조회시 입장가능.gif
  images/gif/회원가입.gif
  src/raid/__test__/raid.service.spec.ts
  src/raid/raid.service.ts
  src/utils/raid.consumer.ts
Labels: documentation, tdd

#75 MODIFY / 랭킹 조회 로직 수정 및 주석 추가
  src/raid/raid.service.ts
  src/raid/rankingInfo.interface.ts
Labels: documentation, fix

#78 REFACTOR / 폴더 정리
  src/common/error.enum.ts
  src/raid/interface/enterBossOption.interface.ts
  src/raid/interface/raidStatus.interface.ts
  src/raid/interface/rankingInfo.interface.ts
  src/raid/raid.consumer.ts
  src/raid/raid.controller.ts
  src/raid/raid.service.ts
Labels: refactor

#79 DOC / 주석 수정, 이미지 파일 추가, swagger 반영
  images/boss-raid-erd.png
  images/gif/유저 조회.gif
  src/raid/entities/raid.entity.ts
  src/raid/raid.controller.ts
  src/raid/raid.service.ts
Labels: documentation

#81 ADD & MODIFY / read me 초안
  README.md
  src/raid/raid.service.ts
Labels: documentation, refactor

#86 DOCS / Swagger User Api 응답 예시 수정
  .gitignore
  src/user/dto/user.response.ts
Labels: documentation

#90 [Task] 스웨거 리스폰스 타입 지정, example, description
  src/raid/dto/raidStatusRes.dto.ts
  src/raid/raid.controller.ts
  src/utils/responseHandler/error.enum.ts
Labels: documentation

#93 ADD & DOCS / read me 수정 및 swagger description 추가
  README.md
  src/raid/raid.controller.ts
Labels: documentation, fix

#95 DOCS / 유저 정보 조회 Api 문서 작업
  src/user/__test__/user.service.spec.ts
  src/user/dto/createUser.dto.ts
  src/user/dto/userInfo.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: documentation

#96 DOCS / 주석 스타일 맞추기, 스웨거 데코레이터 추가
  src/raid/__test__/raid.service.spec.ts
  src/raid/raid.controller.ts
  src/raid/raid.service.ts
  src/utils/responseHandler/response.enum.ts
  test.ts
Labels: documentation

#98 FIX / 최종 수정
  README.md
  src/raid/__test__/raid.service.spec.ts
  src/user/__test__/user.service.spec.ts
  src/utils/helper/raid.consumer.ts
  src/utils/responseHandler/error.enum.ts
  test.ts
Labels: fix

#91 Staging -> Main
  README.md
  src/raid/__test__/raid.service.spec.ts
  src/raid/dto/raidStatusRes.dto.ts
  src/raid/raid.consumer.ts
  src/raid/raid.controller.ts
  src/raid/raid.service.ts
  src/user/__test__/user.service.spec.ts
  src/user/dto/createUser.dto.ts
  src/user/dto/userInfo.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
  src/utils/helper/raid.consumer.ts
  src/utils/responseHandler/error.enum.ts
  src/utils/responseHandler/response.enum.ts
Labels: toMain

#99 FIX / 레이드 모듈, RaidConsumer import 에러 수정
  src/raid/raid.controller.ts
  src/raid/raid.module.ts
  src/utils/responseHandler/response.enum.ts
Labels: bug
